matrix:
  include:
    - stage: test
      name: test_linux_3_7
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - git submodule update --init --recursive
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda install conda=4.6.1
        - conda install -c conda-forge beautifulsoup4=4.7.1 ipython=7.2.0 jupyter=1.0.0 markdown=2.6.11 nbconvert=5.4.0 pelican=4.0.1 "tornado<6"
      script:
        - pelican content
        - python optimise_cache.py ../public/tipuesearch_content.js
        - touch ../public/.nojekyll
      deploy:
        - provider: pages
          repo: thermopot/thermopot.github.io
          target_branch: master
          skip_cleanup: true
          github_token: $GH_TOKEN
          local_dir: ../public
          on:
            branch: master
